services:
  postgres:
    command:
      - postgres
      - -c
      - log_statement=all
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: rewind
      POSTGRES_PASSWORD: rewind
      POSTGRES_DB: rewind
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  echo-server:
    image: ealen/echo-server:0.9.2
    environment:
      - PORT=8000
      - ENABLE__ENVIRONMENT=false
    ports:
      - 9000:8000
